default:
  tags:
    - docker

image: ruby:3.4.2

before_script:
  - apt-get update && apt-get install -y git
  - bundle install

rspec:
  script:
    - bin/rspec

steep:
  script:
    - bundle exec steep check
