module Mobilis::InteractiveDesigner
  class MainMenu < Mobilis::SceneFSM
    attr_accessor metaproject: Mobilis::Project::MetaProject
    attr_accessor selected_rails_project: Mobilis::Project::RailsProject

    def projects: () -> Array[Mobilis::Project::GenericProject]

    def select_rails_project_for_editing: (Mobilis::Project::RailsProject) -> void
    def new_relic_license_key: () -> (String | false)
    def reload!: (?bool) -> true

    def self.state: (Symbol) { () -> void } -> void
    def self.event: (Symbol) { () -> void } -> void

    def self.transition: (untyped) -> void
    def self.after_transition: (untyped) -> void

    def self.prompt: () -> TTY::Prompt
    def go_back: () -> void
    def go_add_project_menu: () -> void
    def go_create_simple_demo_project: () -> void
    def go_create_demo_project: () -> void
    def go_edit_project_menu: () -> void
    def go_show_configuration: () -> void
    def go_edit_links_select_project: () -> void
    def go_save_project: () -> void
    def go_generate: () -> void
    def go_build: () -> void
    def go_quit: () -> void
  end
end

