module Mel
  class SceneFSM
    def prompt: () -> TTY::Prompt
    def spacer: () -> void
    def blank_space: () -> void
    def ask_prompt: (Array[Hash[Symbol, untyped]]) -> untyped
    def choices_per_page: () -> Integer
    def visit_submachine: (Mel::SceneFSM) -> void
    def choices: () -> Array[Hash[Symbol, untyped]]
    def display: () -> (void | false)
    def action: () -> (void | false)
    def still_running?: () -> bool
    def choose_destination: () -> (void | false)
    def decobox: (*Array[String]) -> void

#    def state: (Symbol, untyped) -> void
    def transition: (Hash[Symbol | Array[Symbol] | :any, Symbol]) -> void
    def event: (Symbol) -> void
  end
end

