module Mobilis
  def self.logger: () -> ::Logger

  VERSION: String

  module Project
  end

  module OutputFiles
  end

  module InteractiveDesigner
  end

  module Services
  end

  module OS
  end

  class Error
  end
end

