module TTY
  class Menu
    def default: (*untyped) -> void
    def choice: (*untyped) -> void
  end
  class Prompt
    def select: (String, Array[Hash[Symbol, untyped]], per_page: Integer) -> untyped
    def ask: (String) -> untyped | (String, default: String) -> untyped
    def multi_select: (String) { (Menu) -> void } -> Array[String]
  end
end

