module Mobilis
  class AutoVivify < Hash[Mobilis::auto_key, Mobilis::auto_backing_value]
    def initialize: () -> void
    def []: (Mobilis::auto_key key) -> Mobilis::AutoNode
    def []=: (Mobilis::auto_key key, Mobilis::auto_serial_value value) -> Mobilis::auto_serial_value
    def clean_shrunk: () -> Hash[Symbol, Mobilis::auto_serial_value]
    def deep_compact: (Mobilis::auto_serial_value data) -> Mobilis::auto_serial_value
    def to_h: () -> Hash[Mobilis::auto_key, Mobilis::auto_serial_value]
    def to_serial: () -> Hash[Mobilis::auto_key, Mobilis::auto_serial_value]
    def symbolize_keys_deep: () -> Hash[Symbol, Mobilis::auto_serial_value]
    def materialized?: (*Mobilis::auto_key keys) -> bool
  end

  class AutoNode
    def initialize: (Mobilis::auto_key key) -> void
    def <<: (Mobilis::auto_backing_value value) -> Array[Mobilis::auto_backing_value]
    def merge!: (Hash[Mobilis::auto_key, Mobilis::auto_serial_value] other) -> Hash[Mobilis::auto_key, Mobilis::auto_backing_value]
    def []=: (Mobilis::auto_key key, Mobilis::auto_serial_value value) -> Mobilis::auto_serial_value
    def []: (Mobilis::auto_key key) -> Mobilis::AutoNode
    def to_h: () -> Hash[Mobilis::auto_key, Mobilis::auto_serial_value]
    def to_a: () -> Array[Mobilis::auto_serial_value]
    def to_serial: () -> Mobilis::auto_serial_value
    def inspect: () -> String
    def as_json: (*untyped args) -> Hash[Mobilis::auto_key, Mobilis::auto_serial_value]
    def to_json: (*untyped args) -> String

    private

    def ensure_array!: () -> Array[Mobilis::auto_backing_value]
    def ensure_hash!: () -> Hash[Mobilis::auto_key, Mobilis::auto_backing_value]
    def raise_type_conflict: (Symbol existing) -> bot
    def wrap: (Mobilis::auto_serial_value value) -> Mobilis::auto_serial_value
    def serialize_hash: () -> Hash[Mobilis::auto_key, Mobilis::auto_serial_value]
    def serialize_array: () -> Array[Mobilis::auto_serial_value]
  end
end
