module Mobilis
  class AutoVivify < Hash[untyped, untyped]
    def initialize: () -> void
    def clean_shrunk: () -> untyped
    def deep_compact: (untyped data) -> untyped
    def to_h: () -> Hash[untyped, untyped]
    def to_serial: () -> Hash[untyped, untyped]
    def symbolize_keys_deep: () -> untyped
    def materialized?: (*untyped keys) -> bool
  end

  class AutoNode
    def initialize: (untyped key) -> void
    def <<: (untyped value) -> untyped
    def merge!: (Hash[untyped, untyped] other) -> Hash[untyped, untyped]
    def []=: (untyped key, untyped value) -> untyped
    def []: (untyped key) -> untyped
    def to_h: () -> Hash[untyped, untyped]
    def to_a: () -> Array[untyped]
    def to_serial: () -> untyped
    def inspect: () -> String
    def as_json: (*untyped args) -> Hash[untyped, untyped]
    def to_json: (*untyped args) -> String
  end
end
