module Mobilis
  class ExecutionEnvironment
    attr_reader value: Symbol

    def initialize: (Symbol) -> void

    def is_dev?: () -> bool
    def is_test?: () -> bool
    def is_production?: () -> bool
    def is_staging?: () -> bool

    def to_s: () -> String
  end
end
