module Mobilis::InteractiveDesigner
  def self.add_edit_links_states: (Mobilis::InteractiveDesigner::MainMenu) -> void
  def self.add_project_edit_menu_states: (Mobilis::InteractiveDesigner::MainMenu) -> void
  def self.add_rails_model_edit_states: (Mobilis::InteractiveDesigner::MainMenu) -> void
  def self.add_rails_project_edit_states: (Mobilis::InteractiveDesigner::MainMenu) -> void

  def display: () -> void
  def action: () -> void
  def choices: () -> void



  def go_add_kafka_instance: () -> void
  def go_add_localgem_project: () -> void
  def go_add_mysql_instance: () -> void
  def go_add_omakase_stack_rails_project: () -> void
  def go_add_postgresql_instance: () -> void
  def go_add_prime_stack_rails_project: () -> void
  def go_add_project_menu: () -> void
  def go_add_rack_project: () -> void
  def go_add_redis_instance: () -> void
  def go_back: () -> void
  def go_build: () -> void
  def go_create_demo_project: () -> void
  def go_create_simple_demo_project: () -> void
  def go_edit_kafka_project: () -> void
  def go_edit_links_select_project: () -> void
  def go_edit_links: () -> void
  def go_edit_project_menu: () -> void
  def go_finished: () -> void
  def go_generate: () -> void
  def go_main_menu: () -> void
  def go_quit: () -> void
  def go_rails_add_controller: () -> void
  def go_rails_add_model: () -> void
  def go_rails_controller_edit: () -> void
  def go_rails_edit_controller: () -> void
  def go_rails_field_edit: () -> void
  def go_rails_model_add_field_enter_name: () -> void
  def go_rails_model_add_field_references_select_model: () -> void
  def go_rails_model_add_field_select_type: () -> void
  def go_rails_model_add_field: () -> void
  def go_rails_model_edit: () -> void
  def go_rails_project_add_controller: () -> void
  def go_rails_project_add_index_select_model: () -> void
  def go_rails_project_add_index_to_model: () -> void
  def go_rails_project_add_linked_mysql: () -> void
  def go_rails_project_add_linked_postgres: () -> void
  def go_rails_project_add_linked_redis: () -> void
  def go_rails_project_add_model: () -> void
  def go_rails_project_edit: () -> void
  def go_rails_project_toggle_api_mode: () -> void
  def go_rails_project_toggle_graphql_integration: () -> void
  def go_rails_project_toggle_uuid_primary_keys: () -> void
  def go_save_project: () -> void
  def go_show_configuration: () -> void

   def fancy_tp: (untyped, untyped) -> void
end

