module Mobilis
  module PrettyPrint
    module PrettyPrintable
      def pp: () -> String
      def ppx_fields: (untyped instance) -> untyped
      def ppx_box: (untyped parent) -> untyped
    end

    class DSL
      def self.render: (untyped object, untyped parent) { (Mobilis::PrettyPrint::DSL dsl) -> untyped } -> Mobilis::PrettyPrint::DSL
                     | (untyped object, untyped parent) -> Mobilis::PrettyPrint::DSL

      def initialize: (untyped object, untyped parent) -> void
      def ruby_class: (?untyped object, ?styles: Array[Symbol]) { (Mobilis::PrettyPrint::DSL dsl) -> untyped } -> untyped
                    | (?untyped object, ?styles: Array[Symbol]) -> untyped
      def instance_value: (String label, untyped value) -> untyped
      def child_object: (String label, untyped value) -> untyped
      def env_vars: (untyped value) -> untyped
      def plugins: (untyped plugins) -> untyped
      def ppx_fields: () -> untyped

      private

      def with_depth: (untyped parent_box, untyped object) { (Mobilis::PrettyPrint::DSL dsl) -> untyped } -> untyped
      def depth: () -> Integer
      def top_level?: () -> bool
      def direct_child?: () -> bool
      def distant_relative?: () -> bool
      def child_summary: (untyped obj) -> String
      def truncate_with_ellipsis: (untyped str) -> String
    end
  end
end
