module Mobilis
  module Primitives
    class EmitVar
      attr_reader container_name: String
      attr_reader envfile_name: String?
      attr_reader value: String | Integer | bool
      attr_reader is_alias_only: bool

      def self.for: (String service, String type, String | Integer | bool value, ?do_not_resolve: bool, ?aliased: bool, ?is_alias_only: bool) -> Mobilis::Primitives::EmitVar
      def initialize: (String? container_name, ?String? envfile_name, ?String | Integer | bool value, ?do_not_resolve: bool, ?aliased: bool, ?is_alias_only: bool) -> void
      def has_envfile_name?: () -> bool
      def compose_repr: () -> String
      def compose_value: () -> (String | Integer | bool)
      def container_var_ref: () -> String
      def env_var_ref: () -> String
      def env_repr: () -> String?
      def as: (String new_container_name) -> Mobilis::Primitives::EmitVar
      def key: () -> String?
      def do_not_resolve: () -> bool

      private

      def normalize_name: (String? name) -> String
    end

    class PortMap
      attr_reader internal_port_no: Integer
      attr_reader external_port_no: Integer | String
      attr_reader memo: String
      def initialize: (Integer | String external_port_no, Integer internal_port_no, ?String memo) -> void
      def as_key: () -> String
      def key: () -> (Integer | String)
      def value: () -> Integer
      def to_compose: () -> String
      def name: () -> String
      def ppx_fields: (untyped dsl) -> untyped
    end
  end
end
