class Mobilis::SingleServiceOutputFile < Mobilis::OutputFile
  attr_reader service: Mobilis::Project::GenericProject

  def initialize: (service: Mobilis::Project::GenericProject) -> void
  def project: () -> Mobilis::Project::MetaProject
  def render: () -> String
  def render_data: () -> Hash[String, untyped]
end

