module Mobilis
  class SingleServiceOutputFile[T < Mobilis::Project::GenericProject] < Mobilis::OutputFile
    attr_reader service: T

    def initialize: (T) -> void
    def project: () -> Mobilis::Project::MetaProject
    def render: () -> String
    def render_data: () -> Hash[String, untyped]
    def service_data: () -> Hash[String, untyped]
  end
end
