class Mobilis::SymbolKeyHash < Hash[Symbol, String]
  def []=: (String | Symbol, value: String) -> String
  def []: (String | Symbol) -> String
  def fetch: (String | Symbol, ?default: String) { (String | Symbol) -> String } -> String
  def key?: (String | Symbol) -> bool
  def merge!: (Hash[String | Symbol, String]) -> Mobilis::SymbolKeyHash
  def update: (Hash[String | Symbol, String]) -> Mobilis::SymbolKeyHash
end
