module Mobilis
  class SymbolKeyHash[Value] < Hash[Symbol, Value]
    def []=: (untyped, Value) -> Value
    def []: (untyped) -> Value?
    def fetch: (untyped, Value) -> Value
         | [X] (untyped, X) -> (Value | X)
         | [X] (untyped) { (Symbol) -> X } -> (Value | X)
    def key?: (untyped) -> bool
    def merge!: (Hash[untyped, Value]) -> SymbolKeyHash[Value]
    def update: (Hash[untyped, Value]) -> SymbolKeyHash[Value]
  end
end
