class Mobilis::Project::GenericProject
  include Mobilis::ActionsProjectsTake
  attr_reader metaproject: Mobilis::Project
  attr_reader data: Hash
  def initialize: (a: untyped,t: untyped) -> void
end
