type project_data_hash = {
  name: String,
  type: Symbol,
  controllers?: Array[String],
  models?: Array[String],
  options?: Array[Symbol],
  attributes?: Hash[Symbol, untyped]
}

type meta_project_data_hash = {
  projects: Array[untyped],
  username: String,
  starting_port_no: Integer,
  port_gap: Integer,
  name: String
}

type attributes_hash = {
  projects: Hash[Symbol, untyped],
  new_relic_license_key: String,
} & Hash[Symbol, Integer]  # additional keys are generated dynamically

type writer_mapping_hash = {
  kafka: singleton(Mobilis::Project::KafkaInstance),
  localgem: singleton(Mobilis::Project::LocalgemProject),
  mysql: singleton(Mobilis::Project::MySQLInstance),
  postgresql: singleton(Mobilis::Project::PostgreSQLInstance),
  rack: singleton(Mobilis::Project::RackProject),
  rails: singleton(Mobilis::Project::RailsProject),
  redis: singleton(Mobilis::Project::RedisInstance)
}

module Mobilis::Project
  class MetaProject
    include Mobilis::ActionsProjectsTake

    attr_reader projects: Array[Mobilis::Project::GenericProject]

    def add_kafka_instance: (String) -> Mobilis::Project::KafkaInstance
    def add_localgem_project: (String) -> Mobilis::Project::LocalgemProject
    def add_mysql_instance: (String) -> Mobilis::Project::MySQLInstance
    def add_omakase_stack_rails_project: (String) -> Mobilis::Project::RailsProject
    def add_postgresql_instance: (String) -> Mobilis::Project::PostgreSQLInstance
    def add_prime_stack_rails_project: (String) -> Mobilis::Project::RailsProject
    def add_rack_project: (String) -> Mobilis::Project::RackProject
    def add_rails_project: (String, untyped) -> Mobilis::Project::RailsProject
    def add_redis_instance: (String) -> Mobilis::Project::RedisInstance
    def attributes: () -> void
    def build_rails_builder: () -> void
    def build: () -> void
    def create_datastore_directories: () -> void
    def create_project_instances: () -> void
    def create_rails_builder_dockerfile: () -> void
    def create_rails_builder_gemfile: () -> void
    def create_rails_builder: () -> void
    def datastore_projects: () -> void
    def display: () -> void
    def each_datastore_project: () { (GenericProject) -> void } -> void | () -> Enumerator[GenericProject]
    def each_non_datastore_project: () { (GenericProject) -> void } -> void | () -> Enumerator[GenericProject]
    def each_target_environment: () { (Mobilis::ExecutionEnvironment) -> void}-> void | () -> Enumerator[Mobilis::ExecutionEnvironment]
    def each_project_for_environment: (?::Mobilis::ExecutionEnvironment) -> Enumerator[Mobilis::Project::GenericProject, void] | (?::Mobilis::ExecutionEnvironment) { () -> void } -> void

    def generate_attributes: () -> void
    def generate_env_files: () -> void
    def generate_files: () -> void
    def getwd: () -> String
    def has_datastore_instance?: () -> void
    def has_rails_project?: () -> void
    def initialize: () -> void
    def load_from_file: (String) -> void
    def name=: (String) -> void
    def name: () -> void
    def next_auto_port_no: () -> void
    def non_datastore_projects: () -> void
    def project_by_name: (String) -> Mobilis::Project::GenericProject
    def pull_dev_datastore_instances: () -> void
    def rails_builder_image: () -> void
    def return_to_start_directory: () -> void
    def return_to_target_directory: () -> void
    def runasuser: () -> void
    def save_docker_compose: () -> void
    def save_project: () -> void
    def show: () -> void
    def start_dev_datastore_instances: () -> void
    def target_directory: () -> void
    def to_h: () -> untyped
    def username: () -> void
    def writer_for_project: (Mobilis::Project::GenericProject) -> Mobilis::OutputFile
  end
end
