module Mobilis
  module Project
    class PostgreSQLInstance < GenericProject
      def child_env_vars: () -> Array[String]
      def data_dir: () -> String
      def db_name: (Mobilis::ExecutionEnvironment) -> String
      def env_name: () -> String
      def env_vars: () -> Array[String]
      def env_var: () -> String
      def has_local_build: () -> bool
      def is_datastore_project?: () -> bool
      def password: (Mobilis::ExecutionEnvironment) -> String
      def url: (Mobilis::ExecutionEnvironment) -> String
      def user_id_arg: () -> String
      def username: (Mobilis::ExecutionEnvironment) -> String
      def _empty_vars: () -> Array[String]
    end
  end
end
