module Mobilis
  module Project
    class PostgreSQLInstance < GenericProject
      def child_env_vars: () -> Array[String]
      def data_dir: () -> String
      def db_name: (String) -> String
      def env_name: () -> String
      def env_vars: () -> Array[String]
      def env_var: () -> String
      def global_env_vars: (String) -> Hash[Symbol, untyped]
      def has_local_build: () -> bool
      def is_datastore_project?: () -> bool
      def password: (String) -> String
      def url: (String) -> String
      def user_id_arg: () -> String
      def username: (String) -> String
    end
  end
end
