module Mobilis::Project
  class RailsField
    attr_reader name: String
    attr_reader type: Symbol
    attr_reader rails_model: Mobilis::Project::RailsModel

    def initialize: (name: String, rails_model: Mobilis::Project::RailsModel, type: untyped) -> void
    def line: () -> String
    def for_line: () -> String
    def to_h: () -> { name: String, type: Symbol }
    def to_graphql: () -> String
  end
end
