module Mobilis::Project
  class RedisInstance < GenericProject
    def child_env_vars: () -> void
    def env_name: () -> String
    def data_dir: () -> String
    def has_local_build: () -> bool
    def username: () -> String
    def password: () -> String
    def is_datastore_project?: () -> bool
  end
end
