#!/usr/bin/env ruby

require "pry"

require "mobilis/command_line"
require "mobilis/interactive_designer"

options = Mobilis::CommandLine.parse_args(ARGV)
program = Mobilis::InteractiveDesigner.new
if options[:subcommand] == :load
  program.load_from_file options[:filename]
end
program.go_main_menu

loop do
  puts ""
  puts ""
  puts("  --> Starting loop!! <--")
  program.choose_destination
end
